# Generated by Django 5.2.1 on 2025-05-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealermfx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_vehicles',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
