# Generated by Django 5.2.1 on 2025-05-24 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealermfx', '0002_table_vehicles_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_vehicles',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
