# Generated by Django 5.2.1 on 2025-05-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealermfx', '0003_table_vehicles_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_vehicles',
            name='image',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
