# Generated by Django 5.2.1 on 2025-05-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealermfx', '0004_alter_table_vehicles_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_vehicles',
            name='rented',
            field=models.DateField(blank=True, null=True),
        ),
    ]
